//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.vtt {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemDto", Namespace="http://portal.vtt.ru/data")]
    [System.SerializableAttribute()]
    public partial class ItemDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AvailableQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompatibilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DepthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemLifeTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MainOfficeQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NumberInPackageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceRetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RootGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TransitDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TransitQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailableQuantity {
            get {
                return this.AvailableQuantityField;
            }
            set {
                if ((this.AvailableQuantityField.Equals(value) != true)) {
                    this.AvailableQuantityField = value;
                    this.RaisePropertyChanged("AvailableQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorName {
            get {
                return this.ColorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorNameField, value) != true)) {
                    this.ColorNameField = value;
                    this.RaisePropertyChanged("ColorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Compatibility {
            get {
                return this.CompatibilityField;
            }
            set {
                if ((object.ReferenceEquals(this.CompatibilityField, value) != true)) {
                    this.CompatibilityField = value;
                    this.RaisePropertyChanged("Compatibility");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Depth {
            get {
                return this.DepthField;
            }
            set {
                if ((this.DepthField.Equals(value) != true)) {
                    this.DepthField = value;
                    this.RaisePropertyChanged("Depth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemLifeTime {
            get {
                return this.ItemLifeTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemLifeTimeField, value) != true)) {
                    this.ItemLifeTimeField = value;
                    this.RaisePropertyChanged("ItemLifeTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MainOfficeQuantity {
            get {
                return this.MainOfficeQuantityField;
            }
            set {
                if ((this.MainOfficeQuantityField.Equals(value) != true)) {
                    this.MainOfficeQuantityField = value;
                    this.RaisePropertyChanged("MainOfficeQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameAlias {
            get {
                return this.NameAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.NameAliasField, value) != true)) {
                    this.NameAliasField = value;
                    this.RaisePropertyChanged("NameAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NumberInPackage {
            get {
                return this.NumberInPackageField;
            }
            set {
                if ((this.NumberInPackageField.Equals(value) != true)) {
                    this.NumberInPackageField = value;
                    this.RaisePropertyChanged("NumberInPackage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalNumber {
            get {
                return this.OriginalNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalNumberField, value) != true)) {
                    this.OriginalNumberField = value;
                    this.RaisePropertyChanged("OriginalNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoUrl {
            get {
                return this.PhotoUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoUrlField, value) != true)) {
                    this.PhotoUrlField = value;
                    this.RaisePropertyChanged("PhotoUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceRetail {
            get {
                return this.PriceRetailField;
            }
            set {
                if ((this.PriceRetailField.Equals(value) != true)) {
                    this.PriceRetailField = value;
                    this.RaisePropertyChanged("PriceRetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RootGroup {
            get {
                return this.RootGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.RootGroupField, value) != true)) {
                    this.RootGroupField = value;
                    this.RaisePropertyChanged("RootGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TransitDate {
            get {
                return this.TransitDateField;
            }
            set {
                if ((this.TransitDateField.Equals(value) != true)) {
                    this.TransitDateField = value;
                    this.RaisePropertyChanged("TransitDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TransitQuantity {
            get {
                return this.TransitQuantityField;
            }
            set {
                if ((this.TransitQuantityField.Equals(value) != true)) {
                    this.TransitQuantityField = value;
                    this.RaisePropertyChanged("TransitQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vendor {
            get {
                return this.VendorField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorField, value) != true)) {
                    this.VendorField = value;
                    this.RaisePropertyChanged("Vendor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemRuntimeDto", Namespace="http://portal.vtt.ru/data")]
    [System.SerializableAttribute()]
    public partial class ItemRuntimeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AvailableQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MainOfficeQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TransitQuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailableQuantity {
            get {
                return this.AvailableQuantityField;
            }
            set {
                if ((this.AvailableQuantityField.Equals(value) != true)) {
                    this.AvailableQuantityField = value;
                    this.RaisePropertyChanged("AvailableQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MainOfficeQuantity {
            get {
                return this.MainOfficeQuantityField;
            }
            set {
                if ((this.MainOfficeQuantityField.Equals(value) != true)) {
                    this.MainOfficeQuantityField = value;
                    this.RaisePropertyChanged("MainOfficeQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TransitQuantity {
            get {
                return this.TransitQuantityField;
            }
            set {
                if ((this.TransitQuantityField.Equals(value) != true)) {
                    this.TransitQuantityField = value;
                    this.RaisePropertyChanged("TransitQuantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryDto", Namespace="http://portal.vtt.ru/data")]
    [System.SerializableAttribute()]
    public partial class CategoryDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentIdField, value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemPortionDto", Namespace="http://portal.vtt.ru/data")]
    [System.SerializableAttribute()]
    public partial class ItemPortionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApplication2.vtt.ItemDto[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsApplication2.vtt.ItemDto[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemRuntimePortionDto", Namespace="http://portal.vtt.ru/data")]
    [System.SerializableAttribute()]
    public partial class ItemRuntimePortionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApplication2.vtt.ItemRuntimeDto[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsApplication2.vtt.ItemRuntimeDto[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompatibilityDto", Namespace="http://portal.vtt.ru/data")]
    [System.SerializableAttribute()]
    public partial class CompatibilityDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelBrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelCategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdField, value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelBrand {
            get {
                return this.ModelBrandField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelBrandField, value) != true)) {
                    this.ModelBrandField = value;
                    this.RaisePropertyChanged("ModelBrand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelCategoryName {
            get {
                return this.ModelCategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelCategoryNameField, value) != true)) {
                    this.ModelCategoryNameField = value;
                    this.RaisePropertyChanged("ModelCategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDto", Namespace="http://portal.vtt.ru/data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsFormsApplication2.vtt.OrderFullDto))]
    public partial class OrderDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoodsCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> InvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PaymentInvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentInvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UtdUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoodsCount {
            get {
                return this.GoodsCountField;
            }
            set {
                if ((this.GoodsCountField.Equals(value) != true)) {
                    this.GoodsCountField = value;
                    this.RaisePropertyChanged("GoodsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InvoiceDate {
            get {
                return this.InvoiceDateField;
            }
            set {
                if ((this.InvoiceDateField.Equals(value) != true)) {
                    this.InvoiceDateField = value;
                    this.RaisePropertyChanged("InvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceId {
            get {
                return this.InvoiceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceIdField, value) != true)) {
                    this.InvoiceIdField = value;
                    this.RaisePropertyChanged("InvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineCount {
            get {
                return this.LineCountField;
            }
            set {
                if ((this.LineCountField.Equals(value) != true)) {
                    this.LineCountField = value;
                    this.RaisePropertyChanged("LineCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PaymentInvoiceDate {
            get {
                return this.PaymentInvoiceDateField;
            }
            set {
                if ((this.PaymentInvoiceDateField.Equals(value) != true)) {
                    this.PaymentInvoiceDateField = value;
                    this.RaisePropertyChanged("PaymentInvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentInvoiceId {
            get {
                return this.PaymentInvoiceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentInvoiceIdField, value) != true)) {
                    this.PaymentInvoiceIdField = value;
                    this.RaisePropertyChanged("PaymentInvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Sum {
            get {
                return this.SumField;
            }
            set {
                if ((this.SumField.Equals(value) != true)) {
                    this.SumField = value;
                    this.RaisePropertyChanged("Sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UtdUrl {
            get {
                return this.UtdUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UtdUrlField, value) != true)) {
                    this.UtdUrlField = value;
                    this.RaisePropertyChanged("UtdUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderFullDto", Namespace="http://portal.vtt.ru/data")]
    [System.SerializableAttribute()]
    public partial class OrderFullDto : WindowsFormsApplication2.vtt.OrderDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApplication2.vtt.OrderLineDto[] LinesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsApplication2.vtt.OrderLineDto[] Lines {
            get {
                return this.LinesField;
            }
            set {
                if ((object.ReferenceEquals(this.LinesField, value) != true)) {
                    this.LinesField = value;
                    this.RaisePropertyChanged("Lines");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderLineDto", Namespace="http://portal.vtt.ru/data")]
    [System.SerializableAttribute()]
    public partial class OrderLineDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GtdCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GtdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReservedQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GtdCountry {
            get {
                return this.GtdCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.GtdCountryField, value) != true)) {
                    this.GtdCountryField = value;
                    this.RaisePropertyChanged("GtdCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GtdNumber {
            get {
                return this.GtdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.GtdNumberField, value) != true)) {
                    this.GtdNumberField = value;
                    this.RaisePropertyChanged("GtdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdField, value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReservedQuantity {
            get {
                return this.ReservedQuantityField;
            }
            set {
                if ((this.ReservedQuantityField.Equals(value) != true)) {
                    this.ReservedQuantityField = value;
                    this.RaisePropertyChanged("ReservedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderLineCreationDto", Namespace="http://portal.vtt.ru/data")]
    [System.SerializableAttribute()]
    public partial class OrderLineCreationDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdField, value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderLineStatusDto", Namespace="http://portal.vtt.ru/data")]
    [System.SerializableAttribute()]
    public partial class OrderLineStatusDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoodsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LinesDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderedQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReservedQuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoodsDeleted {
            get {
                return this.GoodsDeletedField;
            }
            set {
                if ((this.GoodsDeletedField.Equals(value) != true)) {
                    this.GoodsDeletedField = value;
                    this.RaisePropertyChanged("GoodsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LinesDeleted {
            get {
                return this.LinesDeletedField;
            }
            set {
                if ((this.LinesDeletedField.Equals(value) != true)) {
                    this.LinesDeletedField = value;
                    this.RaisePropertyChanged("LinesDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderedQuantity {
            get {
                return this.OrderedQuantityField;
            }
            set {
                if ((this.OrderedQuantityField.Equals(value) != true)) {
                    this.OrderedQuantityField = value;
                    this.RaisePropertyChanged("OrderedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReservedQuantity {
            get {
                return this.ReservedQuantityField;
            }
            set {
                if ((this.ReservedQuantityField.Equals(value) != true)) {
                    this.ReservedQuantityField = value;
                    this.RaisePropertyChanged("ReservedQuantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderNoteUpdateResult", Namespace="http://portal.vtt.ru/data")]
    [System.SerializableAttribute()]
    public partial class OrderNoteUpdateResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NoteUpdatedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NoteUpdated {
            get {
                return this.NoteUpdatedField;
            }
            set {
                if ((this.NoteUpdatedField.Equals(value) != true)) {
                    this.NoteUpdatedField = value;
                    this.RaisePropertyChanged("NoteUpdated");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyRateDto", Namespace="http://portal.vtt.ru/data")]
    [System.SerializableAttribute()]
    public partial class CurrencyRateDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ActiveSinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ActiveSince {
            get {
                return this.ActiveSinceField;
            }
            set {
                if ((this.ActiveSinceField.Equals(value) != true)) {
                    this.ActiveSinceField = value;
                    this.RaisePropertyChanged("ActiveSince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://portal.vtt.ru", ConfigurationName="vtt.IPortalService")]
    public interface IPortalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetItems", ReplyAction="http://portal.vtt.ru/IPortalService/GetItemsResponse")]
        WindowsFormsApplication2.vtt.ItemDto[] GetItems(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetItems", ReplyAction="http://portal.vtt.ru/IPortalService/GetItemsResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemDto[]> GetItemsAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetRuntimeItems", ReplyAction="http://portal.vtt.ru/IPortalService/GetRuntimeItemsResponse")]
        WindowsFormsApplication2.vtt.ItemRuntimeDto[] GetRuntimeItems(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetRuntimeItems", ReplyAction="http://portal.vtt.ru/IPortalService/GetRuntimeItemsResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemRuntimeDto[]> GetRuntimeItemsAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetCategories", ReplyAction="http://portal.vtt.ru/IPortalService/GetCategoriesResponse")]
        WindowsFormsApplication2.vtt.CategoryDto[] GetCategories(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetCategories", ReplyAction="http://portal.vtt.ru/IPortalService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.CategoryDto[]> GetCategoriesAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetCategoryItems", ReplyAction="http://portal.vtt.ru/IPortalService/GetCategoryItemsResponse")]
        WindowsFormsApplication2.vtt.ItemDto[] GetCategoryItems(string login, string password, string categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetCategoryItems", ReplyAction="http://portal.vtt.ru/IPortalService/GetCategoryItemsResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemDto[]> GetCategoryItemsAsync(string login, string password, string categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetCategoryRuntimeItems", ReplyAction="http://portal.vtt.ru/IPortalService/GetCategoryRuntimeItemsResponse")]
        WindowsFormsApplication2.vtt.ItemRuntimeDto[] GetCategoryRuntimeItems(string login, string password, string categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetCategoryRuntimeItems", ReplyAction="http://portal.vtt.ru/IPortalService/GetCategoryRuntimeItemsResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemRuntimeDto[]> GetCategoryRuntimeItemsAsync(string login, string password, string categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetItemPortion", ReplyAction="http://portal.vtt.ru/IPortalService/GetItemPortionResponse")]
        WindowsFormsApplication2.vtt.ItemPortionDto GetItemPortion(string login, string password, int from, int to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetItemPortion", ReplyAction="http://portal.vtt.ru/IPortalService/GetItemPortionResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemPortionDto> GetItemPortionAsync(string login, string password, int from, int to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetRuntimeItemsPortion", ReplyAction="http://portal.vtt.ru/IPortalService/GetRuntimeItemsPortionResponse")]
        WindowsFormsApplication2.vtt.ItemRuntimePortionDto GetRuntimeItemsPortion(string login, string password, int from, int to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetRuntimeItemsPortion", ReplyAction="http://portal.vtt.ru/IPortalService/GetRuntimeItemsPortionResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemRuntimePortionDto> GetRuntimeItemsPortionAsync(string login, string password, int from, int to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetItem", ReplyAction="http://portal.vtt.ru/IPortalService/GetItemResponse")]
        WindowsFormsApplication2.vtt.ItemDto GetItem(string login, string password, string itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetItem", ReplyAction="http://portal.vtt.ru/IPortalService/GetItemResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemDto> GetItemAsync(string login, string password, string itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetRuntimeItem", ReplyAction="http://portal.vtt.ru/IPortalService/GetRuntimeItemResponse")]
        WindowsFormsApplication2.vtt.ItemRuntimeDto GetRuntimeItem(string login, string password, string itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetRuntimeItem", ReplyAction="http://portal.vtt.ru/IPortalService/GetRuntimeItemResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemRuntimeDto> GetRuntimeItemAsync(string login, string password, string itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetGoodsCompatibilityInformation", ReplyAction="http://portal.vtt.ru/IPortalService/GetGoodsCompatibilityInformationResponse")]
        WindowsFormsApplication2.vtt.CompatibilityDto[] GetGoodsCompatibilityInformation(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetGoodsCompatibilityInformation", ReplyAction="http://portal.vtt.ru/IPortalService/GetGoodsCompatibilityInformationResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.CompatibilityDto[]> GetGoodsCompatibilityInformationAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetOrderStatus", ReplyAction="http://portal.vtt.ru/IPortalService/GetOrderStatusResponse")]
        WindowsFormsApplication2.vtt.OrderDto GetOrderStatus(string login, string password, string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetOrderStatus", ReplyAction="http://portal.vtt.ru/IPortalService/GetOrderStatusResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.OrderDto> GetOrderStatusAsync(string login, string password, string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetOrderWithLines", ReplyAction="http://portal.vtt.ru/IPortalService/GetOrderWithLinesResponse")]
        WindowsFormsApplication2.vtt.OrderFullDto GetOrderWithLines(string login, string password, string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetOrderWithLines", ReplyAction="http://portal.vtt.ru/IPortalService/GetOrderWithLinesResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.OrderFullDto> GetOrderWithLinesAsync(string login, string password, string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetOrders", ReplyAction="http://portal.vtt.ru/IPortalService/GetOrdersResponse")]
        WindowsFormsApplication2.vtt.OrderDto[] GetOrders(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetOrders", ReplyAction="http://portal.vtt.ru/IPortalService/GetOrdersResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.OrderDto[]> GetOrdersAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/CreateOrder", ReplyAction="http://portal.vtt.ru/IPortalService/CreateOrderResponse")]
        string CreateOrder(string login, string password, WindowsFormsApplication2.vtt.OrderLineCreationDto[] lines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/CreateOrder", ReplyAction="http://portal.vtt.ru/IPortalService/CreateOrderResponse")]
        System.Threading.Tasks.Task<string> CreateOrderAsync(string login, string password, WindowsFormsApplication2.vtt.OrderLineCreationDto[] lines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/AddItem", ReplyAction="http://portal.vtt.ru/IPortalService/AddItemResponse")]
        WindowsFormsApplication2.vtt.OrderLineStatusDto AddItem(string login, string password, string orderId, WindowsFormsApplication2.vtt.OrderLineCreationDto item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/AddItem", ReplyAction="http://portal.vtt.ru/IPortalService/AddItemResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.OrderLineStatusDto> AddItemAsync(string login, string password, string orderId, WindowsFormsApplication2.vtt.OrderLineCreationDto item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/RemoveItem", ReplyAction="http://portal.vtt.ru/IPortalService/RemoveItemResponse")]
        void RemoveItem(string login, string password, string orderId, string itemId, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/RemoveItem", ReplyAction="http://portal.vtt.ru/IPortalService/RemoveItemResponse")]
        System.Threading.Tasks.Task RemoveItemAsync(string login, string password, string orderId, string itemId, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/SetOrderNote", ReplyAction="http://portal.vtt.ru/IPortalService/SetOrderNoteResponse")]
        WindowsFormsApplication2.vtt.OrderNoteUpdateResult SetOrderNote(string login, string password, string orderId, string note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/SetOrderNote", ReplyAction="http://portal.vtt.ru/IPortalService/SetOrderNoteResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.OrderNoteUpdateResult> SetOrderNoteAsync(string login, string password, string orderId, string note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/ExportInvoiceXml", ReplyAction="http://portal.vtt.ru/IPortalService/ExportInvoiceXmlResponse")]
        string ExportInvoiceXml(string login, string password, string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/ExportInvoiceXml", ReplyAction="http://portal.vtt.ru/IPortalService/ExportInvoiceXmlResponse")]
        System.Threading.Tasks.Task<string> ExportInvoiceXmlAsync(string login, string password, string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetUsdRubRate", ReplyAction="http://portal.vtt.ru/IPortalService/GetUsdRubRateResponse")]
        WindowsFormsApplication2.vtt.CurrencyRateDto GetUsdRubRate(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.vtt.ru/IPortalService/GetUsdRubRate", ReplyAction="http://portal.vtt.ru/IPortalService/GetUsdRubRateResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.CurrencyRateDto> GetUsdRubRateAsync(string login, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPortalServiceChannel : WindowsFormsApplication2.vtt.IPortalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PortalServiceClient : System.ServiceModel.ClientBase<WindowsFormsApplication2.vtt.IPortalService>, WindowsFormsApplication2.vtt.IPortalService {
        
        public PortalServiceClient() {
        }
        
        public PortalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PortalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApplication2.vtt.ItemDto[] GetItems(string login, string password) {
            return base.Channel.GetItems(login, password);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemDto[]> GetItemsAsync(string login, string password) {
            return base.Channel.GetItemsAsync(login, password);
        }
        
        public WindowsFormsApplication2.vtt.ItemRuntimeDto[] GetRuntimeItems(string login, string password) {
            return base.Channel.GetRuntimeItems(login, password);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemRuntimeDto[]> GetRuntimeItemsAsync(string login, string password) {
            return base.Channel.GetRuntimeItemsAsync(login, password);
        }
        
        public WindowsFormsApplication2.vtt.CategoryDto[] GetCategories(string login, string password) {
            return base.Channel.GetCategories(login, password);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.CategoryDto[]> GetCategoriesAsync(string login, string password) {
            return base.Channel.GetCategoriesAsync(login, password);
        }
        
        public WindowsFormsApplication2.vtt.ItemDto[] GetCategoryItems(string login, string password, string categoryId) {
            return base.Channel.GetCategoryItems(login, password, categoryId);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemDto[]> GetCategoryItemsAsync(string login, string password, string categoryId) {
            return base.Channel.GetCategoryItemsAsync(login, password, categoryId);
        }
        
        public WindowsFormsApplication2.vtt.ItemRuntimeDto[] GetCategoryRuntimeItems(string login, string password, string categoryId) {
            return base.Channel.GetCategoryRuntimeItems(login, password, categoryId);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemRuntimeDto[]> GetCategoryRuntimeItemsAsync(string login, string password, string categoryId) {
            return base.Channel.GetCategoryRuntimeItemsAsync(login, password, categoryId);
        }
        
        public WindowsFormsApplication2.vtt.ItemPortionDto GetItemPortion(string login, string password, int from, int to) {
            return base.Channel.GetItemPortion(login, password, from, to);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemPortionDto> GetItemPortionAsync(string login, string password, int from, int to) {
            return base.Channel.GetItemPortionAsync(login, password, from, to);
        }
        
        public WindowsFormsApplication2.vtt.ItemRuntimePortionDto GetRuntimeItemsPortion(string login, string password, int from, int to) {
            return base.Channel.GetRuntimeItemsPortion(login, password, from, to);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemRuntimePortionDto> GetRuntimeItemsPortionAsync(string login, string password, int from, int to) {
            return base.Channel.GetRuntimeItemsPortionAsync(login, password, from, to);
        }
        
        public WindowsFormsApplication2.vtt.ItemDto GetItem(string login, string password, string itemId) {
            return base.Channel.GetItem(login, password, itemId);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemDto> GetItemAsync(string login, string password, string itemId) {
            return base.Channel.GetItemAsync(login, password, itemId);
        }
        
        public WindowsFormsApplication2.vtt.ItemRuntimeDto GetRuntimeItem(string login, string password, string itemId) {
            return base.Channel.GetRuntimeItem(login, password, itemId);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.ItemRuntimeDto> GetRuntimeItemAsync(string login, string password, string itemId) {
            return base.Channel.GetRuntimeItemAsync(login, password, itemId);
        }
        
        public WindowsFormsApplication2.vtt.CompatibilityDto[] GetGoodsCompatibilityInformation(string login, string password) {
            return base.Channel.GetGoodsCompatibilityInformation(login, password);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.CompatibilityDto[]> GetGoodsCompatibilityInformationAsync(string login, string password) {
            return base.Channel.GetGoodsCompatibilityInformationAsync(login, password);
        }
        
        public WindowsFormsApplication2.vtt.OrderDto GetOrderStatus(string login, string password, string orderId) {
            return base.Channel.GetOrderStatus(login, password, orderId);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.OrderDto> GetOrderStatusAsync(string login, string password, string orderId) {
            return base.Channel.GetOrderStatusAsync(login, password, orderId);
        }
        
        public WindowsFormsApplication2.vtt.OrderFullDto GetOrderWithLines(string login, string password, string orderId) {
            return base.Channel.GetOrderWithLines(login, password, orderId);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.OrderFullDto> GetOrderWithLinesAsync(string login, string password, string orderId) {
            return base.Channel.GetOrderWithLinesAsync(login, password, orderId);
        }
        
        public WindowsFormsApplication2.vtt.OrderDto[] GetOrders(string login, string password) {
            return base.Channel.GetOrders(login, password);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.OrderDto[]> GetOrdersAsync(string login, string password) {
            return base.Channel.GetOrdersAsync(login, password);
        }
        
        public string CreateOrder(string login, string password, WindowsFormsApplication2.vtt.OrderLineCreationDto[] lines) {
            return base.Channel.CreateOrder(login, password, lines);
        }
        
        public System.Threading.Tasks.Task<string> CreateOrderAsync(string login, string password, WindowsFormsApplication2.vtt.OrderLineCreationDto[] lines) {
            return base.Channel.CreateOrderAsync(login, password, lines);
        }
        
        public WindowsFormsApplication2.vtt.OrderLineStatusDto AddItem(string login, string password, string orderId, WindowsFormsApplication2.vtt.OrderLineCreationDto item) {
            return base.Channel.AddItem(login, password, orderId, item);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.OrderLineStatusDto> AddItemAsync(string login, string password, string orderId, WindowsFormsApplication2.vtt.OrderLineCreationDto item) {
            return base.Channel.AddItemAsync(login, password, orderId, item);
        }
        
        public void RemoveItem(string login, string password, string orderId, string itemId, int count) {
            base.Channel.RemoveItem(login, password, orderId, itemId, count);
        }
        
        public System.Threading.Tasks.Task RemoveItemAsync(string login, string password, string orderId, string itemId, int count) {
            return base.Channel.RemoveItemAsync(login, password, orderId, itemId, count);
        }
        
        public WindowsFormsApplication2.vtt.OrderNoteUpdateResult SetOrderNote(string login, string password, string orderId, string note) {
            return base.Channel.SetOrderNote(login, password, orderId, note);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.OrderNoteUpdateResult> SetOrderNoteAsync(string login, string password, string orderId, string note) {
            return base.Channel.SetOrderNoteAsync(login, password, orderId, note);
        }
        
        public string ExportInvoiceXml(string login, string password, string orderId) {
            return base.Channel.ExportInvoiceXml(login, password, orderId);
        }
        
        public System.Threading.Tasks.Task<string> ExportInvoiceXmlAsync(string login, string password, string orderId) {
            return base.Channel.ExportInvoiceXmlAsync(login, password, orderId);
        }
        
        public WindowsFormsApplication2.vtt.CurrencyRateDto GetUsdRubRate(string login, string password) {
            return base.Channel.GetUsdRubRate(login, password);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.vtt.CurrencyRateDto> GetUsdRubRateAsync(string login, string password) {
            return base.Channel.GetUsdRubRateAsync(login, password);
        }
    }
}
